### ISSUE TITLE
Configurable Form Values to Filter

### ISSUE THREAD

**Issue by mattgwagner** [serilog-web/classic#12]
Right now, fields with the key "password" are filtered out of the log properties by default.

It would be nice if this was configurable, in case we wanted to add things like SSN's or Credit Card Number fields from our forms.

**Comment by nblumhardt** [comment]
Closed via #13

**Comment by mattgwagner** [comment]
Awesome, thanks for the quick review and merge!

I saw you had AppVeyor configured for the project, but wasn't producing a build on merge for this. Out of my own selfish interest, when do you usually produce a build and NuGet package for this? Not planning on using it until Monday anyway, but figured I'd follow up.

**Comment by nblumhardt** [comment]
Looks like the AppVeyor pipeline is stuck somehow, it'd normally fire on any commit to master as you expected. Investigating now. Thanks!

**Comment by nblumhardt** [comment]
http://help.appveyor.com/discussions/problems/2818-build-not-triggering-commit-message-not-detected
