### ISSUE TITLE
ApplicationLifecycleModule.IsEnabled = false; not working

### ISSUE THREAD

**Issue by empz** [serilog-web/classic#20]
I have 3 slots of an Azure Web Application running slightly different versions of the same ASP.NET MVC web app.

I'm logging to an external Seq server through Serilog with some enrichers from SerilogWeb.Classic. Each slot has its own ApiKey so I can differentiate each event in the Seq dashboard.

I don't want to log every HTTP request and this was working fine until now. All of a sudden one of the slots started logging every HTTP request. So I went back and make sure `ApplicationLifecycleModule.IsEnabled = false;` was there. It's there. I also went further and added `ApplicationLifecycleModule.RequestLoggingLevel = Serilog.Events.LogEventLevel.Verbose;` but it's not working either, the requests are still being logged with level Information.

The only real difference between the slots during deployment is the web.config that gets transformed in order to modify some appSettings, nothing strange.

What could be causing this behaviour? Is there another place where this could be overwritten?

Just to provide more information, this is the method that gets called in Global.asax `Application_Start()` method.

``` c#
    public static class SerilogConfig
    {
        private const string SeqServerUrl = "http://mySeqUrl";
        private static readonly string ApiKey = ConfigurationManager.AppSettings["Seq.ApiKey"];

        public static void Initialize()
        {
            ApplicationLifecycleModule.IsEnabled = false; // disable logging every HTTP request
            ApplicationLifecycleModule.RequestLoggingLevel = Serilog.Events.LogEventLevel.Verbose;

            Log.Logger = new LoggerConfiguration()
                .WriteTo.Seq(SeqServerUrl, apiKey: ApiKey)
                .WriteTo.RollingFile(AppDomain.CurrentDomain.BaseDirectory + "App_Data\\" + "Logs\\" + "{Date}.txt")
                .Enrich.WithMachineName()            
                .Enrich.With(new HttpRequestClientHostIPEnricher(true))
                .Enrich.With(new HttpRequestClientHostNameEnricher())
                .Enrich.With(new HttpRequestRawUrlEnricher())
                .Enrich.With(new HttpRequestUrlReferrerEnricher())
                .Enrich.With(new HttpRequestUserAgentEnricher())              
                .CreateLogger();

            Log.Information("Application started.");
        }
    }
```

**Comment by nblumhardt** [comment]
Hi - it's most likely that there are two different assemblies at work here. Do you have `Serilog.Extras.Web.dll` as well as `SerilogWeb.Classic.dll` in the bin folder?

**Comment by empz** [comment]
That's correct. The old `Serilog.Extras.Web.dll` was sitting in the bin folder next to the new one and causing the issue. Deleted it and now it's working.

Thank you
