### ISSUE TITLE
Enable enrichers from web.config appsettings?

### ISSUE THREAD

**Issue by fspataro-zz** [serilog-web/classic#34]
Is it possible to enable the enrichers (ie HttpRequestIdEnricher) from the web.config using the Serilog.Settings.AppSettings package? I've tried the following as well as many variations in the web.config but it never outputs the RequestId.  (NOTE... the request id comes thru if I use the .Enrich.With<> line in the code. 

`<add key="serilog:using:Classic" value="SerilogWeb.Classic" />
<add key="serilog:enrich:With" value="HttpRequestIdEnricher" />`

Thanks

**Comment by nblumhardt** [comment]
Hi Fred,

The configuration only works for enrichers that extend `LoggerEnrichmentConfiguration` with an extension method like `Enrich.WithHttpRequestId()`. When an extension method is available, it can be called with `<add key="serilog:enrich:WithHttpRequestId" />`.

I don't think this library provides the required extension methods - if anyone's interested in putting a PR together, it would be a worthwhile improvement.

There's an example of the kind of method I mean here: https://github.com/serilog/serilog-enrichers-environment/blob/dev/src/Serilog.Enrichers.Environment/EnvironmentLoggerConfigurationExtensions.cs#L32

Best regards,
Nick

**Comment by fspataro-zz** [comment]
Thanks Nick!
That's the sense I was getting looking thru the code but wasn't sure.
