### ISSUE TITLE
How to write own local Enrichers

### ISSUE THREAD

**Issue by kurosch** [serilog-web/classic#36]
Hello,

I was trying to extend the existing enrichers for specific ones we need for our logging and realized that this is not possible due to HttpContextCurrent being an internal class.

So I was wondering how to write custom Enrichers? 

For example we need to extract a specific cookie and log it as well.

I do not mind sending PR for the Enrichers, however a different solution to the problem would be appreciated.

**Comment by nblumhardt** [comment]
Hi @kurosch - `HttpContextCurrent` is just a thin wrapper for `HttpContext.Current` from ASP.NET. You should be able to use it directly in your custom enricher.

**Comment by kurosch** [comment]
Thank you for clarification.
