### ISSUE TITLE
Request for new functionality in HttpRequestEnricher

### ISSUE THREAD

**Issue by asierrollograbe** [serilog-web/classic#41]
Hello. 

I’d like to have some new functionality in the HttpRequestIdEnricher class because in some scenarios, it’s necessary to propagate the ActivityId for later tracking. 

Use case:  
1-	You have a Web Application that calls a Web Service.
2-	The user logs in, and starts to use the Web Application. The HttpRequestId is created for this request. 
3-	The application calls to Web Service, passing the HttpRequestId in the http Header. 
4-	The web service (via HTTPModule or global.asax) captures the header. 
a.	In the present design, the Web Service has a different ActivityId than the Web Application. 
b.	[CHANGE] We would like to be able to set the Web App ActivityId in the HttpRequestId of the Web Service. This way we could spread the ActivityId to any app or service (instead having different ones for each app/service). That would be very useful for tracking the ActivityId later, using tools like Graylog (we have an Enricher that writes in GELF format).  

One possible solution is to include in the HttpRequestIdEnricher class a method like this one:
public static bool SetCurrentHttpRequestId(Guid requestId)
        {
            if (HttpContext.Current == null)
            {
                return false;
            }

            var requestIdItem = HttpContext.Current.Items[RequestIdItemName];
            if (!HttpContext.Current.Items.Contains(RequestIdItemName))
            {
                HttpContext.Current.Items.Add(RequestIdItemName, requestId);
            }
            else
            {
                HttpContext.Current.Items[RequestIdItemName] = requestId;
            }

            return true;
        }

With this change, we could set the HttpRequestId in the Web Service, and in case of failure we could consult the logs from the Web Application and any Web Services that this application called using the same ActivityId to track ALL the activity through different applications.

Regards

**Comment by nblumhardt** [comment]
Hi @asierrollograbe - thanks for the suggestion. Given the different semantics in your scenario - you're propagating activity is, not collecting a single unique id for the handling of a single HTTP request - would it be reasonable to just create a new, custom, `ActivityIdEnricher` for this? Cheers!

**Comment by asierrollograbe** [comment]
Thank you for your suggestion
Wouldn’t it be interesting to have this functionality in the library? It seems to be a common scenario, I’m sure it will be useful. 
Would there be any problem if I update the project with my solution?
Kind regards.

**Comment by nblumhardt** [comment]
Propagating correlation ids like this is definitely interesting and worthwhile, but I think this project should stick a bit closer to the raw HTTP request handling infrastructure rather than add anything higher-level.

Would a possible alternative be:

```csharp
    Enrich.WithHttpHeader("X-Some-Header", "PropertyName")
```

This would fit with the goals here, and hopefully cover the `ActivityId` scenario cleanly, too. What do you think?

**Comment by mrstebo** [comment]
I had the exact requirements for this kind of thing. So I created a separate enricher that you can add if you need it.

https://github.com/ekmsystems/serilog-enrichers-correlation-id

But as has already been mentioned, this is probably not the scope of this particular project. So better to leave it as an another dependency of your own project 👍

**Comment by asierrollograbe** [comment]
Thanks mrstebo , it's very useful to me.
