### ISSUE TITLE
Calling cfg.LogAtLevel to set the LogEventLevel seems to disable HTTP request logging?

### ISSUE THREAD

**Issue by timcapps** [serilog-web/classic#54]
I'm using a LoggingLevelSwitch and writing to a Seq sink. For some reason when I call

`SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Debug));`

We cease to get log events for the HTTP requests (however we still get logs for requests resulting in a 500 level HttpResponse)

My log level for the Seq API key token is set to verbose.

Here is an example of the configuration initialization.. perhaps I'm doing something wrong?

```
 internal void InitializeLogger()
{
    var levelSwitch = new LoggingLevelSwitch();

    var loggerConfiguration = new LoggerConfiguration()
            .Destructure.ByTransforming<System.Data.SqlClient.SqlException>(ex =>
            {
                // This particular exception is causing problems in Serilog when it gets decomposed into properties and values, hence the need to decompose it to something that won't have a problem
                // SQL System Error Messages (i.e. ex.Number): https://msdn.microsoft.com/en-us/library/cc645603(v=sql.105).aspx
                return new { ex.Message, ex.Server, ex.StackTrace, ex.HResult, ex.Data, ex.ErrorCode, ex.Procedure, ex.Number, ex.LineNumber, ex.Errors, ex.ClientConnectionId, ex.Class };
            })
            .Destructure.ByTransforming<System.Data.Common.DbException>(ex =>
            {
                return new { ex.Message, ex.Source, ex.StackTrace, ex.HResult, ex.Data, ex.ErrorCode };
            })
            .Enrich.FromLogContext()
            .Enrich.WithExceptionDetails()
            .Enrich.WithProperty("Application Server", Environment.MachineName)
            .Enrich.WithProperty("Application", "Enterprise Web API")
            .Enrich.WithHttpRequestClientHostIP()
            .Enrich.WithHttpRequestClientHostName()
            .Enrich.WithHttpRequestUrl()
            .Enrich.WithHttpRequestUrlReferrer()
            .Enrich.WithHttpRequestUserAgent()
            .Enrich.WithHttpSessionId()
            .Enrich.WithUserName()
            .Enrich.WithWebApiActionName()
            .Enrich.WithWebApiControllerName()
            .Enrich.WithWebApiRouteData()
            .Enrich.WithWebApiRouteTemplate();


    
    loggerConfiguration.WriteTo.Seq(
    ConfigurationManager.AppSettings["SeqServerUrl"],
    apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
    controlLevelSwitch: levelSwitch,
    compact: true);
    

    Log.Logger = loggerConfiguration.CreateLogger();
	
    // If below line is commented out, all HTTP requests are logged... if left, only 500 responses are logged
    SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Debug));

}
```

We are also using the Classic-Webapi package if that has some affect...
Am I doing something out of order here?

**Comment by timcapps** [comment]
I just noticed that if I call
`SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Warning));`
 with any level above Information it works as expected.. However, anything Debug or below it does not work

**Comment by tsimbalar** [comment]
Hi Timothy,

Thanks for taking the time to create a detailed issue 👍  !

I think the behavior you are observing is **the expected behavior** (but I may be wrong) ... I'll explain you why :)

The default configuration for Serilog is to only process events with logging level of ***Information* or higher** (*Warning*, *Error*, *Fatal*), and any event of level lower than that (*Debug*, *Verbose*) is simply ignored and will never reach a sink (see [this page in the Serilog wiki](https://github.com/serilog/serilog/wiki/Configuration-Basics#minimum-level) for more details). 

By default, *SerilogWeb.Classic* generates writes log events at level *Information* for each HTTP request.

When you *lower the level* of log events generated by *SerilogWeb.Classic* (for instance `SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Debug))`), the events are still generated but are ignored by the Serilog *pipeline*.

What you need to do in that case is to configure *Serilog* to write events of level *Debug* to its sinks. This is done thanks to the `.MinimumLevel.XXX()` methods on `LoggerConfiguration` : 
```csharp
loggerConfiguration.MinimumLevel.Debug()
```

(this can then be filtered more granularly *per-sink* using the `restrictedToMinimumLevel` argument you usually find on Sinks)


I hope this helps ! 

(by the way, I see you are reading some configuration from the `web.config` file ... if you haven't yet, you should probably take a look at [*Serilog.Settings.AppSettings*](https://github.com/serilog/serilog-settings-appsettings) to partially load Serilog configuration from config file)

**Comment by timcapps** [comment]
Thank you for your quick reply! (and the AppSettings tip, I'll check that out)

The intellisense for the .LogAtLevel method states that it will "Configure at which level the HTTP requests are logged. Default is Information"

When I call .LogAtLevel(LogEventLevel.Warning) the HTTP requests are logged at the warning level. 
When I pass in Debug or Verbose I would expect it to continue to log the HTTP requests but log them at the level I specified. Is this not the case?

I've retested this by changing my loggerConfiguration as follows:
```
 loggerConfiguration.WriteTo.Seq(
                ConfigurationManager.AppSettings["SeqServerUrl"],
                 Serilog.Events.LogEventLevel.Verbose,
                apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
                controlLevelSwitch: levelSwitch,
                compact: true);
```

And testing with this call:
`SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Debug));`

For reference the API key I'm logging to has a log level set to accept evens Verbose and above:
![image](https://user-images.githubusercontent.com/4118647/41479331-cf421ee6-7098-11e8-94c0-4ddc3b4a47ad.png)

**Comment by timcapps** [comment]
I've also tried the following with the same result:

```
  loggerConfiguration.WriteTo.Seq(
                ConfigurationManager.AppSettings["SeqServerUrl"],
                 Serilog.Events.LogEventLevel.Verbose,
                apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
                controlLevelSwitch: levelSwitch,
                compact: true).MinimumLevel.Verbose();
```

Perhaps I'm configuring this wrong somewhere?

**Comment by tsimbalar** [comment]
Oh wait, I hadn't noticed the usage of a `LoggingLevelSwitch` passed to the *Seq* sink ...

The normal usage would be something like (see https://nblumhardt.com/2016/02/remote-level-control-in-serilog-using-seq/ for more details) : 

```csharp
var levelSwitch = new LoggingLevelSwitch();

var loggerConfiguration = new LoggerConfiguration()
    .MinimumLevel.ControlledBy(levelSwitch)
    .Destructure.By(/* ... */)
    .Enrich.From(/*...*/)
    .WriteTo.Seq(
        ConfigurationManager.AppSettings["SeqServerUrl"],
        apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
        controlLevelSwitch: levelSwitch,
        compact: true);

Log.Logger = loggerConfiguration.CreateLogger();
	
SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Debug));
```

Note the the same instance of `LoggingLevelSwitch` is used both in : 
- `.MinimumLevel.ControlledBy(levelSwitch)`
- `.WriteTo.Seq(/*...*/ controlLevelSwitch: levelSwitch)`

This is actually the thing that makes the *Serilog pipeline* vary the minimum level based on the setting configured in Seq (API Key configuration).

(note that this is also supported in the `appSettings` configuration : https://github.com/serilog/serilog-sinks-seq#dynamic-log-level-control )

So I think you are missing the `.MinimumLevel.ControlledBy(levelSwitch)` part ... 

And if that still doesn't solve it, then maybe it is because you have split the `LoggerConfiguration` method calls in multiple lines instead of chaining ... but I think it should be fine ... Still I would have done : 

```csharp

    var loggerConfiguration = new LoggerConfiguration()
            .Destructure.ByTransforming<System.Data.SqlClient.SqlException>(/**/)
            .Destructure.ByTransforming<System.Data.Common.DbException>(/**/)
            .Enrich.FromLogContext()
            .Enrich.WithExceptionDetails()
            .Enrich.WithProperty("Application Server", Environment.MachineName)
            .Enrich.WithProperty("Application", "Enterprise Web API")
            .Enrich.WithHttpRequestClientHostIP()
            .Enrich.WithHttpRequestClientHostName()
            .Enrich.WithHttpRequestUrl()
            .Enrich.WithHttpRequestUrlReferrer()
            .Enrich.WithHttpRequestUserAgent()
            .Enrich.WithHttpSessionId()
            .Enrich.WithUserName()
            .Enrich.WithWebApiActionName()
            .Enrich.WithWebApiControllerName()
            .Enrich.WithWebApiRouteData()
            .Enrich.WithWebApiRouteTemplate();
    
    // WriteTo.Seq returns the logger configuration for chaining ... 
    loggerConfiguration = loggerConfiguration.WriteTo.Seq(
        ConfigurationManager.AppSettings["SeqServerUrl"],
        apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
        controlLevelSwitch: levelSwitch,
        compact: true);
    
    Log.Logger = loggerConfiguration.CreateLogger();
```

instead of 

```csharp
    var loggerConfiguration = new LoggerConfiguration()
            .Destructure.ByTransforming<System.Data.SqlClient.SqlException>(/**/)
            .Destructure.ByTransforming<System.Data.Common.DbException>(/**/)
            .Enrich.FromLogContext()
            .Enrich.WithExceptionDetails()
            .Enrich.WithProperty("Application Server", Environment.MachineName)
            .Enrich.WithProperty("Application", "Enterprise Web API")
            .Enrich.WithHttpRequestClientHostIP()
            .Enrich.WithHttpRequestClientHostName()
            .Enrich.WithHttpRequestUrl()
            .Enrich.WithHttpRequestUrlReferrer()
            .Enrich.WithHttpRequestUserAgent()
            .Enrich.WithHttpSessionId()
            .Enrich.WithUserName()
            .Enrich.WithWebApiActionName()
            .Enrich.WithWebApiControllerName()
            .Enrich.WithWebApiRouteData()
            .Enrich.WithWebApiRouteTemplate();
    
    loggerConfiguration.WriteTo.Seq(
    ConfigurationManager.AppSettings["SeqServerUrl"],
    apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
    controlLevelSwitch: levelSwitch,
    compact: true);
    
    Log.Logger = loggerConfiguration.CreateLogger();
```

**Comment by tsimbalar** [comment]
(also the default level of `LoggingLevelSwitch` is *Information* ... you may want to use `new LoggingLevelSwitch(LogEventLevel.Debug)` or another value)

**Comment by timcapps** [comment]
Adding .MinimumLevel.ControlledBy() fixed the issue! Below is what I wound up with. Thank you for your help and patience with me!

```
internal void InitializeLogger()
        {
            var levelSwitch = new LoggingLevelSwitch(LogEventLevel.Verbose);

            var loggerConfiguration = new LoggerConfiguration()
                    .MinimumLevel.ControlledBy(levelSwitch)
                    .Destructure.ByTransforming<System.Data.SqlClient.SqlException>(/**/)
                    .Destructure.ByTransforming<System.Data.Common.DbException>(/**/)
                    .Enrich.FromLogContext()
                    .Enrich.WithExceptionDetails()
                    .Enrich.WithProperty("Application Server", Environment.MachineName)
                    .Enrich.WithProperty("Application", "Enterprise Web API")
                    .Enrich.WithHttpRequestClientHostIP()
                    .Enrich.WithHttpRequestClientHostName()
                    .Enrich.WithHttpRequestUrl()
                    .Enrich.WithHttpRequestUrlReferrer()
                    .Enrich.WithHttpRequestUserAgent()
                    .Enrich.WithHttpSessionId()
                    .Enrich.WithUserName()
                    .Enrich.WithWebApiActionName()
                    .Enrich.WithWebApiControllerName()
                    .Enrich.WithWebApiRouteData()
                    .Enrich.WithWebApiRouteTemplate();


            if (!Debugger.IsAttached)
            {
                loggerConfiguration.WriteTo.Seq(
                ConfigurationManager.AppSettings["SeqServerUrl"],
                apiKey: ConfigurationManager.AppSettings["SeqApiKey"],
                controlLevelSwitch: levelSwitch,
                compact: true);
            }
            else
                loggerConfiguration.WriteTo.Console();

            Log.Logger = loggerConfiguration.CreateLogger();
            SerilogWebClassic.Configure(cfg => cfg.LogAtLevel(LogEventLevel.Verbose));

        }

```

**Comment by tsimbalar** [comment]
Glad I could help ! 😃
