### ISSUE TITLE
EnableFormDataLogging not logging anything with WebApi

### ISSUE THREAD

**Issue by Dypso** [serilog-web/classic#64]
I have used this sink along with classic-webapi and use this syntax at configuration 
```

 .EnableFormDataLogging(forms => forms
                    .AtLevel(LogEventLevel.Information)
                    .FilterKeywords(new[] { "password", "authToken" })
                )
```

But when I post data to my webApi I see no any information logged ... Is that even possible ? Or does it only make sense on a ASP.Net MVC project ?

**Comment by tsimbalar** [comment]
`FormDataLogging` logs data posted through actual "Web Forms", i.e. via an actual "http form" , with `application/x-www-form-urlencoded` or similar.

In Web API, you typically `POST` contents as `application/json` , so you don't actually have explicit fields/values.

So to sum up : that can work only with WebForms or MVC :)

**Comment by tsimbalar** [comment]
maybe related to https://github.com/serilog-web/classic/issues/35 ?
