### ISSUE TITLE
When using Serilog version 1.5.7, web classic is looking for version 1.4.0.

### ISSUE THREAD

**Issue by ryanande** [serilog-web/classic#7]
When using SerilogWeb.Classic with Serilog version 1.5.7 the following error occurs;

`Could not load file or assembly 'Serilog, Version=1.4.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Tried BindingRedirect which did not resolve the issue, probably due to the sn.

Does it make sense to update this assembly to reference the newer version of Serilog?

**Comment by nblumhardt** [comment]
Fixed in #8.
