### ISSUE TITLE
ASP .NET Core enrichers?

### ISSUE THREAD

**Issue by ffMathy** [serilog-web/classic#71]
How do I get the enrichers for ASP .NET Core? You refer to the `Serilog.AspNetCore` package, but it doesn't contain the nice enrichers that the classic package does.

**Comment by tsimbalar** [comment]
Hi Mathias,

Would this article by @nblumhardt help point you in the right direction ? 

https://nblumhardt.com/2019/10/serilog-mvc-logging/

You might have to some of it manually, but it seems manageable.

**Comment by ffMathy** [comment]
Ah yes. Thanks!
