### ISSUE TITLE
IIS Web application hang up after multiple requests stuck on "Begin request"

### ISSUE THREAD

**Issue by jonataspc** [serilog-web/classic#80]
We had a problematic scenario today which a .NET Framework 4.8 ASP.NET application hung up after queuing multiple requests stuck on "Begin request" state, on the __DynamicModule_SerilogWeb.Classic.ApplicationLifecycleModule module.

That same web application runs simultaneously on another 4 servers (webfarm), and we haven't had any issues on those at that moment. And just to be specific, the problem happened hours after the application startup. 
We also noted that CPU usage went down when the requests started to queue. 

![image](https://github.com/serilog-web/classic/assets/13005203/660348cd-d6e1-4c76-94aa-4aadf09ea0a5)

After a while: 
![image](https://github.com/serilog-web/classic/assets/13005203/0f9680e9-94f7-44b5-9e4d-9927c8993cbd)

I have looked on the source code and the `OnBeginRequest` is where a simple stopwatch is added to the application context.
Is there a chance of concurrency on that part that might cause this behavior?

**Comment by tsimbalar** [comment]
Really sorry, but I have no clue 😭

**Comment by tsimbalar** [comment]
This project is no longer being maintained and we are going to archive the SerilogWeb Repositories. 

see:
- https://github.com/serilog-web/classic/issues/82
